import {
  Aperture,
  ArrowUp,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardPaste,
  Clock,
  CloudOff,
  CloudUpload,
  Copy,
  Crown,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  Flag,
  Globe,
  Grid2x2,
  HardDrive,
  Hourglass,
  ImagePlus,
  Images,
  Info,
  Link,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  MapPin,
  MapPinOff,
  Moon,
  Pencil,
  Phone,
  Play,
  Plus,
  QrCode,
  RefreshCw,
  ScanLine,
  Share,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SunMoon,
  Trash2,
  TriangleAlert,
  UserPlus,
  Users,
  Video,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react-native';

import { useColors } from '@/theme/ThemeProvider';
import { iconSize, iconStroke, type ColorTokens } from '@/theme/tokens';

/** One outline icon set (Lucide), one stroke width, a handful of sizes. */
const icons = {
  add: Plus,
  addPhoto: ImagePlus,
  album: Images,
  alert: CircleAlert,
  aperture: Aperture,
  back: ChevronLeft,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  checkCircle: CircleCheck,
  chevron: ChevronRight,
  chevronDown: ChevronDown,
  circle: Circle,
  clock: Clock,
  close: X,
  closeCircle: CircleX,
  copy: Copy,
  crown: Crown,
  download: Download,
  edit: Pencil,
  eye: Eye,
  eyeOff: EyeOff,
  globe: Globe,
  grid: Grid2x2,
  hourglass: Hourglass,
  info: Info,
  link: Link,
  location: MapPin,
  locationOff: MapPinOff,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  more: Ellipsis,
  moon: SunMoon,
  night: Moon,
  offline: WifiOff,
  paste: ClipboardPaste,
  people: Users,
  phone: Phone,
  play: Play,
  qr: QrCode,
  refresh: RefreshCw,
  report: Flag,
  scan: ScanLine,
  share: Share,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  storage: HardDrive,
  trash: Trash2,
  unlock: LockOpen,
  upload: CloudUpload,
  uploadOff: CloudOff,
  arrowUp: ArrowUp,
  userAdd: UserPlus,
  video: Video,
  warning: TriangleAlert,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  size = 'md',
  color = 'text',
  rawColor,
  strokeWidth = iconStroke,
}: {
  name: IconName;
  size?: keyof typeof iconSize | number;
  color?: keyof ColorTokens;
  rawColor?: string;
  strokeWidth?: number;
}) {
  const colors = useColors();
  const Cmp = icons[name];
  const px = typeof size === 'number' ? size : iconSize[size];
  return <Cmp size={px} color={rawColor ?? (colors[color] as string)} strokeWidth={strokeWidth} absoluteStrokeWidth />;
}
